apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aufumw86n-python 
  janus-idp.io/tekton: aufumw86n-python
  backstage.io/kubernetes-id: aufumw86n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aufumw86n-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  