apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aufumw86n-python
  janus-idp.io/tekton: aufumw86n-python
  backstage.io/kubernetes-id: aufumw86n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aufumw86n-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
